### ISSUE TITLE
Add workflow to build PDF remotely

### ISSUE THREAD

**Issue by martonvago** [seedcase-project/seedcase-sprout#1326]

**Comment by martonvago** [comment]
Draft action:
```yaml
name: Build PDF

on:
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    env:
        QUARTO_PYTHON: .venv/bin/python3
    steps:
        - name: Check out repository
          uses: actions/checkout@v4
  
        - name: Install uv
          uses: astral-sh/setup-uv@v6
          with:
            # Install a specific version of uv.
            # uv recommends to set the version for best practice.
            version: 0.6.13
            # To have a faster CI time, enable cache between runs.
            enable-cache: true
            # Reset the cache if the lock file changes.
            cache-dependency-glob: uv.lock
  
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version-file: pyproject.toml
  
        - name: Install the project and its dependencies
          run: |
              uv sync --all-extras --dev
              source .venv/bin/activate
  
        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
  
        - name: Spell check repo
          uses: crate-ci/typos@v1.32.0
  
        - name: Install TinyTeX and Chromium
          run: |
            uv run quarto install tinytex
            uv run quarto install chromium

        - name: Render PDF
          run: uv run quarto render --profile pdf --to pdf

        - name: Clean up Mermaid figures
          run: find docs -name "mermaid-figure-*.png" -delete

        - name: Upload PDF
          uses: actions/upload-artifact@v4
          with:
            name: seedcase-sprout
            path: |
                _book/seedcase-sprout.pdf
            overwrite: true

```

Currently this fails at the render step because it cannot create the PDF from the generated tex file. I think this is because of the custom code block wrapping config in `_quarto-pdf.yml`, or somehow related to the `fvextra` package used there. I've added the error logs for posterity. The version of xelatex used remotely and locally is the same.

If I remove the custom config in `_quarto-pdf.yml`, it does render, but it looks worse. Even things that shouldn't be affected by the custom config look worse, so something is clearly different between local and remote rendering 🤷 🤔 ...

[logs.txt](https://github.com/user-attachments/files/20350235/logs.txt)
