### ISSUE TITLE
Add navbar dropdown for reference to split documentation of `core` and `lib`

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#947]
Inspired by [Shiny for Python](https://shiny.posit.co/py/), it could be nice to split the reference docs into `core` and `lib`.

![Image](https://github.com/user-attachments/assets/b0ac7c12-a60b-46a7-a2f0-0f59d0a44269)

**Comment by signekb** [comment]
Alternatively, we just keep it as is and have a collective reference page and add `lib` to `_quarto.yml` as so: 

```
        # (end of core config)
        - path_resources
        - path_sprout_global

    - title: "Lib functions"
      desc: "Lib functions that support the creation and management of data packages and data resources."

    - subtitle: "Data package functions"
      desc: "Functions to work with and manage data packages, but not the data resources within them."
      package: "seedcase_sprout.lib"
      contents:
        - function1
        - function2
```
